---
- name: consul service config file
  with_items: services
  template: >
    src=consul-service.json.j2
    dest={{ consul_config_dir }}/{{ item.name }}.json
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  notify:
    - restart consul
