---
- name: Install platanus base consul server environment
  hosts: tag_provision_platanus_negroku:&~tag_consul.*
  remote_user: ubuntu
  sudo: true

  vars:
    - consul_version: 0.5.2
    - consul_join_at_start: "true"
    - consul_servers: ['10.10.1.211','10.10.1.211']
    - consul_bootstrap_expect: 3
    - consul_client_address: 0.0.0.0

  roles:
    - role: consul
      services:
        - name: eye
          port: 65093
          checks:
            - id: eye-api-check
              name: HTTP check on port 65093
              http: http://localhost:65093
              interval: 30s
              timeout: 5s
      notify:
        - restart consul

  post_tasks:
    - name: restart consul
      action: service name=consul state=restarted
